title: "Tianqi Kou"
url: "https://koutianqi.info"
baseurl: ""
markdown: kramdown
theme: null
plugins: []
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
permalink: pretty

# Site variables
cv_available: true
cv_pdf: "/assets/Tianqi Kou CV-7.pdf"

